config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :categories
  resources :products
  get 'about', to: 'welcome#about_us'
  get 'contact', to: 'welcome#contact_us'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact_us
  end

  def about_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/index.html.erb
<section class="hero-about" id="hero">
  <div class="containers">
    <h5 class="sub-heading mt-5" style="font-size: 2rem;">
        Panairet
    </h5>
  </div>
</section>

<p id="notice"><%= notice %></p>

<section class="discover-our-menu">
  <div class="containers">
    <div class="restaurant-info row">
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 restaurant-description padding-right animatable bounceInLeft">
        <div class="global-headline">
          <h2 class="headline headline-dark">
            Panairet e Demokratia - Komerc
          </h2>
          <%= image_tag "Logo.png" %>
        </div>
      </div>
      <div class=" col-lg-6 col-md-6 col-sm-12 col-xs-12 image-group padding-right animate-left">
          <%= image_tag 'Panairet/Panairi1.jpg' %>
          <%= image_tag 'Panairet/Panairi2.jpg' %>
          <%= image_tag 'Panairet/Panairi3.jpg' %>
          <%= image_tag 'Panairet/Panairi4.jpg' %>
          <%= image_tag 'Panairet/Panairi5.jpg' %>
          <%= image_tag 'Panairet/Panairi6.jpg' %>
          <%= image_tag 'Panairet/Panairi7.jpg' %>
          <%= image_tag 'Panairet/Panairi8.jpg' %>
          <%= image_tag 'Panairet/Panairi9.jpg' %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemokratijaKomerc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="/app/assets/stylesheets/application.css.scss" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="./index.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/ac72ca25e9.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  </head>

  <body>
    <header class="containe">
      <nav class="navbar navbar-expand-lg navbar-light mt-2">
        <%= image_tag 'Logo.png', class: 'navbar-brand' %><%= link_to  "Demokratia-Komerc", root_path, class:"navbar-brand nav-link logo text-white" %>
        <button class="navbar-toggler text-white" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon text-white"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto ">
            <li class="nav-item"><%= link_to  "Home", root_path, class:"nav-link text-white" %></li>
            <li class="nav-item"><%= link_to  "About Us", about_path, class:"nav-link text-white" %></li>
            <li class="nav-item"><%= link_to  "Contact", contact_path, class:"nav-link text-white" %></li>
            <li class="nav-item"><%= link_to  "Product", products_path, class:"nav-link text-white" %></li>
            <li class="nav-item"><%= link_to  "Fair", categories_path, class:"nav-link text-white" %></li>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <div class="containers">
        <div class="back-to-top">
          <a href="">
            <i class="fas fa-chevron-up"></i>
          </a>
        </div>
        <div class="footer-content">
          <div class=" animate-up">
            <h4>About Demokratija - Komerc</h4>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae nam temporibus, accusamus quos ut pariatur praesentium in dolor magnam quidem.</p>
          </div>
          <div class=" animate-bottom">
            <div class="social-menu">
              <h4>Follow us</h4>
              <div class="social-icons">
                <ul>
                  <li><a href="https://www.instagram.com/gzim921/"><i class="fab fa-instagram"></i></a></li>
                  <li><a href="https://web.facebook.com/gzim.iseni95"><i class="fab fa-facebook"></i></a></li>
                </ul>
              </div>
              <div class="newsletter-container">
                <h1>Made by: Gzim Iseni</h1>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/products/index.html.erb
<section class="hero-about" id="hero">
  <div class="containers">
    <h5 class="sub-heading mt-5" style="font-size: 2rem;">
      Produktet | Производи
    </h5>
  </div>
</section>
<p id="notice"><%= notice %></p>

<section class="discover-our-menu">
  <div class="containers">
    <div class="restaurant-info row">
      <div class="global-headline">
        <%= image_tag "Produktet/Suxhuk1.jpg", class: 'photo' %>
        <br>
        <br>
        <%= image_tag "Produktet/suxhuk-zgare.jpg", class: 'photo' %>
        <br>
        <br>
        <%= image_tag "Produktet/Mish-i-thate.jpg", class: 'photo' %>
        <br>
        <br>
        <%= image_tag "Produktet/Suxhuk2.jpg", class: 'photo' %>
        <br>
        <br>
        <%= image_tag "Produktet/suxhuk-shtepie.jpg", class: 'photo' %>
        <br>
        <br>
        <%= image_tag "Produktet/Cajna.jpg", class: 'photo' %>
        <br>
        <br>
        <%= image_tag "Produktet/Kulen.jpg", class: 'photo' %>
        <br>
        <br>
        <%= image_tag "Produktet/batak.jpg", class: 'photo' %>
        <br>
        <br>
        <%= image_tag "Produktet/virshel.jpg", class: 'photo' %>
      </div>
    </div>
  </div>
</section>

app/views/welcome/about_us.html.erb
<section class="hero-about" id="hero">
  <div class="containers">
    <h5 class="sub-heading mt-5" style="font-size: 2rem;">
      THE BEST QUALITY
    </h5>
    <h1 class="headline mt-5" style="font-size: 1.5rem;">About US</h1>
  </div>
</section>

<div class="container my-5 about text-center">
  <h1 class="text-center mt-5" style="font-size: 2.5rem; font-weight: bold">About Our Story</h1>
  <h2 class="sub-heading mt-5">
    <%= image_tag "Logo.png", class: "logo" %>
  </h2>
  <p class="mt-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. 
    Numquam perspiciatis omnis minima ipsa quam repellendus 
    reprehenderit facilis quia corporis saepe ad temporibus sequi, 
    praesentium, non rem earum aut iusto accusamus quaerat, suscipit
    fugiat vitae laboriosam beatae. Nisi itaque saepe temporibus fuga
    vel laboriosam sint nesciunt dolores ea, consequuntur fugit obcaecati
    exercitationem quia. Sapiente, tenetur id debitis dolorum veniam aperiam. Quia?
  </p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
    Numquam perspiciatis omnis minima ipsa quam repellendus 
    reprehenderit facilis quia corporis saepe ad temporibus sequi, 
    praesentium, non rem earum aut iusto accusamus quaerat, suscipit
    fugiat vitae laboriosam beatae. Nisi itaque saepe temporibus fuga
    vel laboriosam sint nesciunt dolores ea, consequuntur fugit obcaecati
    exercitationem quia. Sapiente, tenetur id debitis dolorum veniam aperiam. Quia?
  </p>
  <p class="mt-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. 
    Numquam perspiciatis omnis minima ipsa quam repellendus 
    reprehenderit facilis quia corporis saepe ad temporibus sequi, 
    praesentium, non rem earum aut iusto accusamus quaerat, suscipit
    fugiat vitae laboriosam beatae. Nisi itaque saepe temporibus fuga
    vel laboriosam sint nesciunt dolores ea, consequuntur fugit obcaecati
    exercitationem quia. Sapiente, tenetur id debitis dolorum veniam aperiam. Quia?
  </p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
    Numquam perspiciatis omnis minima ipsa quam repellendus 
    reprehenderit facilis quia corporis saepe ad temporibus sequi, 
    praesentium, non rem earum aut iusto accusamus quaerat, suscipit
    fugiat vitae laboriosam beatae. Nisi itaque saepe temporibus fuga
    vel laboriosam sint nesciunt dolores ea, consequuntur fugit obcaecati
    exercitationem quia. Sapiente, tenetur id debitis dolorum veniam aperiam. Quia?
  </p>
</div>

app/views/welcome/contact_us.html.erb
<section class="hero-contact" id="hero">
  <div class="containers">
    <h5 class="sub-heading mt-5" style="font-size: 2rem;">
      Na Kontaktoni | Контактирајте не | Contact Us
    </h5>
  </div>
</section>


<div class="container">
  <div class="row">
    <div class="col-sm text-center">
      <h1 class="text-center my-5" style="font-size: 2.5rem; font-weight: bold">Contact US</h1>
      <h2 class="sub-heading mt-5">
        <%= image_tag "Logo.png", class: "logo" %>
      </h2>
    </div>
  </div>
    <div class="row my-5">
      <div  class="col-md-6">
        <h5>Address: <small class="text-muted">Skopje - Saraj</small></h5>
        <h5>Email: <small class="text-muted">demokraijakomerc@gmail.com</small></h5>
        <h5>Contact: <small class="text-muted">(+389-70-278-105) - (+389-71-278-105)</small></h5>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<section class="hero" id="hero">
  <div class="containers">
    <h2 class="sub-heading mt-5">
      <%= image_tag "Logo.png", class: "logo" %>
    </h2>
    <h2 class="sub-heading mt-5">
      Demokratija<span class="first-letter">-</span>Komerc
    </h2>
    <h1 class="headline mt-5">Industria e Mishit - Saraj</h1>
    <h2 class="sub-heading mt-5">
      Демократија<span class="first-letter">-</span>Комерц
    </h2>
    <h1 class="headline mt-5">Месна Индустрија - Сарај</h1>
    <div class=" headline-description">
      <div class="single-animation mt-5">
        <%= link_to  "Rreth Nesh | За Нас | About Us", about_path, class:"btn text-white" %>
      </div>
    </div>
  </div>
</section>
<!-- Hero ends-->

<section class="discovery-our-story">
  <div class="container">
    <div class="restaurant-info row">
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 restaurant-description padding-right animatable bounceInLeft">
        <div class="global-headline">
          <h2 class="headline headline-dark"> ABOUT US</h2>
        </div>
        <p>
          Ne perpunim | На Преработка
        </p>
        <%= link_to  "Rreth Nesh | За Нас | About Us", about_path, class:"btn" %>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 restaurant-info-img animatable bounceInRight">
        <%= image_tag 'Logo.png' %>
      </div>
    </div>
  </div>
</section>
<!-- Discover of our story -->

<div class="container my-5">
  <h2 class="headline headline-dark text-center">Produktet | Производи</h2>
  <div class="">
    <div class="row">
  
    </div>
  </div>
</div>
<!--category end-->

<section class="discover-our-menu">
  <div class="containers">
    <div class="restaurant-info row">
      <div class=" col-lg-6 col-md-6 col-sm-12 col-xs-12 restaurant-description animate-right">
        <div class="global-headline">
          <h2 class="headline headline-dark">SPECIAL OFFER</h2>
        </div>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit.
          Mollitia quisquam iusto unde incidunt eaque laudantium
          cupiditate minus quibusdam similique fuga totam assumenda,
          ipsam delectus numquam quo aut quasi officiis ex eum?
          Dignissimos atque enim inventore eligendi ratione fugiat
        </p>
        <%= link_to  "Produktet", products_path, class:"btn" %>
      </div>
      <div class=" col-lg-6 col-md-6 col-sm-12 col-xs-12 image-group padding-right animate-left">
        <%= image_tag "Produktet/Suxhuk1.jpg" %>
        <%= image_tag "Produktet/Suxhuk2.jpg" %>
        <%= image_tag "Produktet/suxhuk-zgare.jpg" %>
        <%= image_tag "Produktet/suxhuk-shtepie.jpg" %>
        <%= image_tag "Produktet/Mish-i-thate.jpg" %>
        <%= image_tag "Produktet/Cajna.jpg" %>
        <%= image_tag "Produktet/Kulen.jpg" %>
        <%= image_tag "Produktet/batak.jpg" %>
        <%= image_tag "Produktet/virshel.jpg" %>
      </div>
    </div>
  </div>
</section>